name: Version Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verify Package Version
        run: |
          old_version=$(git show main:package.json | grep "version" | cut -d'"' -f4)
          new_version=$(grep "version" package.json | cut -d'"' -f4)

          if [[ "$old_version" == "$new_version" ]]; then
            echo "Version is unchanged"
            exit 1
          fi